config/routes.rb
Rails.application.routes.draw do
  
  root :to => "brainiac#index"

  get '/takeQuiz' => 'brainiac#takequiz'
  
  devise_for :users
  resources :quizzes
  resources :real_quizzes

  match ':controller(/:action(/:id))', :via => :get

end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
end

app/models/real_quiz.rb
class RealQuiz < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/brainiac_controller.rb
class BrainiacController < ApplicationController
  def index
  end

  def takequiz
  	@quizzes = Quiz.all
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      params.require(:quiz).permit(:question, :opt1, :opt2, :opt3, :opt4, :answer, :category)
    end
end

app/controllers/real_quizzes_controller.rb
class RealQuizzesController < ApplicationController
  before_action :set_real_quiz, only: [:show, :edit, :update, :destroy]

  def index
    @real_quizzes = RealQuiz.all
    respond_with(@real_quizzes)
  end

  def show
    respond_with(@real_quiz)
  end

  def new
    @real_quiz = RealQuiz.new
    respond_with(@real_quiz)
  end

  def edit
  end

  def create
    @real_quiz = RealQuiz.new(real_quiz_params)
    @real_quiz.save
    respond_with(@real_quiz)
  end

  def update
    @real_quiz.update(real_quiz_params)
    respond_with(@real_quiz)
  end

  def destroy
    @real_quiz.destroy
    respond_with(@real_quiz)
  end

  private
    def set_real_quiz
      @real_quiz = RealQuiz.find(params[:id])
    end

    def real_quiz_params
      params.require(:real_quiz).permit(:quiz_name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brainiac_helper.rb
module BrainiacHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/real_quizzes_helper.rb
module RealQuizzesHelper
end

app/views/brainiac/index.html.erb
<h1>Brainiac#index</h1>
<p>Find me in app/views/brainiac/index.html.erb</p>

<%= link_to 'New Quiz', new_quiz_path %><br /><br />
<%= link_to 'View all Quizzes', quizzes_path %>

<br />

<%= link_to 'Take Quiz', takeQuiz_path %>
 

app/views/brainiac/takequiz.html.erb
<h1>Listing quizzes</h1>

<table class="main_options">
  <thead>
    <tr>
      <th>Question</th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.question %></td>
        <td><%= quiz.opt1 %></td>
        <td><%= quiz.opt2 %></td>
        <td><%= quiz.opt3 %></td>
        <td><%= quiz.opt4 %></td>
        <td><%= quiz.category %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brainiac</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p>Some more tests right here!!! :)</p>

<% if notice %>
	<p class = "alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
	<p class = "alert alert-danger"><%= alert %></p>
<% end %>

<!-- Adding sign-up and login links -->
<p class="navbar-text pull-right">
<% if user_signed_in? %>
		Logged in as <strong><%= current_user.email %></strong>
	<%= link_to 'Edit Profile', edit_user_registration_path, :class =>'navbar-link' %> |
	<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
<% else %>
	<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
	<% link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>	


<%= yield %>
<style>
	.main_options table{
		background-color: #eee;
	}

</style>

</body>
</html>

app/views/quizzes/_form.html.erb
<%= form_for(@quiz) do |f| %>
  <% if @quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
      <% @quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>



  <div class="field">
    <%= f.label :opt1 %><br>
    <%= f.text_field :opt1 %>
  </div>

  <div class="field">
    <%= f.label :opt2 %><br>
    <%= f.text_field :opt2 %>
  </div>

  <div class="field">
    <%= f.label :opt3 %><br>
    <%= f.text_field :opt3 %>
  </div>

  <div class="field">
    <%= f.label :opt4 %><br>
    <%= f.text_field :opt4 %>
  </div>

  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quizzes/edit.html.erb
<h1>Editing quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<h1>Listing quizzes</h1>

<table class="main_options">
  <thead>
    <tr>
      <th>Question</th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
      <th>Answer</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= quiz.question %></td>
        <td><%= quiz.opt1 %></td>
        <td><%= quiz.opt2 %></td>
        <td><%= quiz.opt3 %></td>
        <td><%= quiz.opt4 %></td>
        <td><%= quiz.answer %></td>
        <td><%= quiz.category %></td>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quiz', new_quiz_path %>

app/views/quizzes/new.html.erb
<h1>New quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @quiz.question %>
</p>

<p>
  <strong>Option 1:</strong>
  <%= @quiz.opt1 %>
</p>

<p>
  <strong>Option 2:</strong>
  <%= @quiz.opt2 %>
</p>

<p>
  <strong>Option 3:</strong>
  <%= @quiz.opt3 %>
</p>

<p>
  <strong>Option 4:</strong>
  <%= @quiz.opt4 %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @quiz.answer %>
</p>

<p>
  <strong>Category:</strong>
  <%= @quiz.category %>
</p>

<%= link_to 'Edit', edit_quiz_path(@quiz) %> |
<%= link_to 'Back', quizzes_path %>

app/views/real_quizzes/_form.html.erb
<%= form_for(@real_quiz) do |f| %>
  <% if @real_quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@real_quiz.errors.count, "error") %> prohibited this real_quiz from being saved:</h2>

      <ul>
      <% @real_quiz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quiz_name %><br>
    <%= f.text_field :quiz_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/real_quizzes/edit.html.erb
<h1>Editing real_quiz</h1>

<%= render 'form' %>

<%= link_to 'Show', @real_quiz %> |
<%= link_to 'Back', real_quizzes_path %>

app/views/real_quizzes/index.html.erb
<h1>Listing real_quizzes</h1>

<table>
  <thead>
    <tr>
      <th>Quiz name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @real_quizzes.each do |real_quiz| %>
      <tr>
        <td><%= real_quiz.quiz_name %></td>
        <td><%= real_quiz.user_id %></td>
        <td><%= link_to 'Show', real_quiz %></td>
        <td><%= link_to 'Edit', edit_real_quiz_path(real_quiz) %></td>
        <td><%= link_to 'Destroy', real_quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Real quiz', new_real_quiz_path %>

app/views/real_quizzes/new.html.erb
<h1>New real_quiz</h1>

<%= render 'form' %>

<%= link_to 'Back', real_quizzes_path %>

app/views/real_quizzes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quiz name:</strong>
  <%= @real_quiz.quiz_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @real_quiz.user_id %>
</p>

<%= link_to 'Edit', edit_real_quiz_path(@real_quiz) %> |
<%= link_to 'Back', real_quizzes_path %>